<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-R0QK2O8" name="com.mercuryTravel.tests.HomePageTest" tests="2" failures="1" timestamp="04 Mar 2019 03:14:02 GMT" time="6.530" errors="0">
  <testcase name="verifyTitleOfTheHomepage" time="0.038" classname="com.mercuryTravel.tests.HomePageTest">
    <failure type="java.lang.AssertionError" message="expected [Mercury Travels: Holiday Packages, Flight Booking, Hotels, Forex, Visa &amp; Travel Insurance 1] but found [Mercury Travels: Holiday Packages, Flight Booking, Hotels, Forex, Visa &amp; Travel Insurance]">
      <![CDATA[java.lang.AssertionError: expected [Mercury Travels: Holiday Packages, Flight Booking, Hotels, Forex, Visa & Travel Insurance 1] but found [Mercury Travels: Holiday Packages, Flight Booking, Hotels, Forex, Visa & Travel Insurance]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.mercuryTravel.tests.HomePageTest.verifyTitleOfTheHomepage(HomePageTest.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- verifyTitleOfTheHomepage -->
  <testcase name="verifyUserLoginWithCorrectCredentials" time="6.492" classname="com.mercuryTravel.tests.HomePageTest"/>
</testsuite> <!-- com.mercuryTravel.tests.HomePageTest -->
